apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : shop
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: shop
  source:
    path   : "shop/kubernetes-manifests.yaml"
    repoURL: "git@github.com:miklashevich/argocd.git"
    targetRevision: HEAD


  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true         
